### ISSUE TITLE
Unable to test the python code

### ISSUE THREAD

**Issue by asprakash** [SharviElectronics/SIM-A7670C---4G-LTE-Modem#1]
Tried the python to connect the SIM7670C Modem. However, the python code is not working since the following information are missing. 
- Which version of python to use, Python 2.x or Python 3.x?
- Is the code assumed that it is running on Raspberry Pi kind of embedded boards?. If so, share more in detail of the testing environment.
- No information about TX/RX pin details.
- No need of APN details to connect the internet?.

**Comment by Rajkumar181** [comment]
- You can use Python any version
- Yes for Raspberry Pi board
- RX and TX pin you can check in Raspbrry PI board (GPIO14 and GPIO15), enable using raspberry-config, sudo raspi-config >Interfacing Options->Serial->Serial login shell disable,Serial interface enabled
- no need APN details

**Comment by asprakash** [comment]
Hi Rajkumar,
Thanks for your prompt reply.

Your serial port instruction can be suitable on any Raspberry Pi zero/w/PI3/PI4/PI5 boards. However, your python code uses the Machine (and network) library which belongs to Micropython, not regular Python which is run by these RPI boards. But, Raspberry Pi Pico can support this script. So how to test your python script on RPI3/4/5 boards?. My requirement is Raspberry Pi zero/w/PI3/PI4/PI5 boards, not RPI Pico.
